trigger:
- main

pool:
  name: local

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
- checkout: self
  fetchDepth: 0
    

- script: |
    java -version
  env:
    JAVA_HOME: $(JAVA_HOME_8_X64)
    PATH: $(JAVA_HOME_8_X64)/bin;$(PATH)


- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: 'yuriarthurestudos'
    organization: 'test'
    scannerMode: 'CLI'
    configMode: 'manual'
    projectKey: 'yuriarthurestudos_test'
    projectName: 'test'

# Run Code Analysis task
- task: SonarCloudAnalyze@2

# Publish Quality Gate Result task
- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'